{
    "EmployeeCode": "Nv99c",
    "FullName": "nhanvatcapcaoo",
    "Gender": 1,
    "DateOfBirth": "2023-10-06",
    "PhoneNumber": "",
    "Email": null,
    "Address": null,
    "IdentityNumber": "",
    "IdentityDate": null,
    "IdentityPlace": null,
    "JoinDate": null,
    "MartialStatus": null,
    "EducationalBackground": null,
    "QualificationId": null,
    "DepartmentId": "3f8e6896-4c7d-15f5-a018-75d8bd200d7c",
    "PositionId": null,
    "WorkStatus": null,
    "PersonalTaxCode": null,
    "Salary": null,
    "PositionCode": null,
    "PositionName": null,
    "DepartmentCode": "PB-1170",
    "DepartmentName": "Phòng Công Nghệ Thông Tin",
    "QualificationName": null,
    "GenderName": "Nam",
    "EducationalBackgroundName": null,
    "MartialStatusName": null,
    "CreatedDate": "2023-10-07T00:12:09",
    "CreatedBy": null,
    "ModifiedDate": "2023-10-07T00:29:04",
    "ModifiedBy": null
}